version: '3.4'

services:
  catalogdb:
    image: postgres

  cartdb:
    image: postgres
  
  distributedcache:
    image: redis   

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile

  cartapi:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: Services/Cart/CartAPI/Dockerfile

volumes:
  postgres_catalog:
  postgres_cart:
